/* =====================================================================
HOLOMED — WIDGET DO ASSISTENTE 3D (Projeto Infosaúde Jovem CCB)
Usa o conteúdo do dados.js (perguntas, textos).
Arquivos necessários na pasta img/:
  holomed.glb -> modelo 3D com animações nomeadas:
                   Idle, Wave, Talk, Empathy, Thinking, Joy, Surprise
                     holomed.png -> render estático (fallback automático se o GLB falhar)
                     ===================================================================== */
                     (function () {
                       "use strict";

                         var GLB_URL = "img/holomed.glb";
                           var IMG_FALLBACK = "img/holomed.png";

                             /* ---------- estrutura do widget ---------- */
                               var botao = document.createElement("button");
                                 botao.id = "holomed-botao";
                                   botao.type = "button";
                                     botao.setAttribute("aria-label", "Abrir assistente HoloMed");
                                       botao.setAttribute("aria-expanded", "false");
                                         botao.innerHTML =
                                             '<svg viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="3" ' +
                                                 'stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">' +
                                                     '<path d="M24 40C10 30 4 22 4 14a10 10 0 0 1 18-6 10 10 0 0 1 18 6c0 8-6 16-20 26Z"/></svg>';

                                                       var painel = document.createElement("section");
                                                         painel.id = "holomed-painel";
                                                           painel.hidden = true;
                                                             painel.setAttribute("aria-label", "Assistente HoloMed");
                                                               painel.innerHTML =
                                                                   '<header id="holomed-topo"><strong>HoloMed</strong><span>Assistente de IA · Infosaúde Jovem CCB</span></header>' +
                                                                       '<div id="holomed-palco">' +
                                                                             '<model-viewer id="holomed-mv" camera-controls autoplay shadow-intensity="1.1" exposure="1.1" ' +
                                                                                   'interaction-prompt="none" style="opacity:0"></model-viewer>' +
                                                                                         '<img id="holomed-fallback" src="' + IMG_FALLBACK + '" alt="Assistente HoloMed flutuando">' +
                                                                                               '<span id="holomed-anel" aria-hidden="true"></span>' +
                                                                                                   '</div>' +
                                                                                                       '<div id="holomed-expressoes" role="group" aria-label="Animações do HoloMed"></div>' +
                                                                                                           '<div id="holomed-chat" aria-live="polite"></div>' +
                                                                                                               '<form id="holomed-form">' +
                                                                                                                     '<input id="holomed-input" type="search" placeholder="Pergunte sobre saúde…" autocomplete="off" aria-label="Pergunta para o assistente">' +
                                                                                                                           '<button type="submit">Enviar</button>' +
                                                                                                                               '</form>';

                                                                                                                                 document.body.appendChild(botao);
                                                                                                                                   document.body.appendChild(painel);

                                                                                                                                     var mv = painel.querySelector("#holomed-mv");
                                                                                                                                       var fallback = painel.querySelector("#holomed-fallback");
                                                                                                                                         var chat = painel.querySelector("#holomed-chat");
                                                                                                                                           var form = painel.querySelector("#holomed-form");
                                                                                                                                             var input = painel.querySelector("#holomed-input");
                                                                                                                                               var barra = painel.querySelector("#holomed-expressoes");

                                                                                                                                                 /* ---------- animações 3D (nomes devem bater com o GLB) ---------- */
                                                                                                                                                   function tocar(nome, ms) {
                                                                                                                                                       if (mv.hidden || !mv.availableAnimations.length) return;
                                                                                                                                                           mv.animationName = nome;
                                                                                                                                                               clearTimeout(tocar.t);
                                                                                                                                                                   tocar.t = setTimeout(function () { mv.animationName = "Idle"; }, ms || 2600);
                                                                                                                                                                     }

                                                                                                                                                                       mv.addEventListener("load", function () {
                                                                                                                                                                           fallback.hidden = true;
                                                                                                                                                                               mv.style.opacity = "1";
                                                                                                                                                                                   mv.availableAnimations.forEach(function (nome) {
                                                                                                                                                                                         var b = document.createElement("button");
                                                                                                                                                                                               b.type = "button";
                                                                                                                                                                                                     b.textContent = nome;
                                                                                                                                                                                                           b.addEventListener("click", function () { tocar(nome, 3000); });
                                                                                                                                                                                                                 barra.appendChild(b);
                                                                                                                                                                                                                     });
                                                                                                                                                                                                                       });

                                                                                                                                                                                                                         mv.addEventListener("error", function () {
                                                                                                                                                                                                                             mv.hidden = true; /* mantém PNG com animação CSS (flutuar + anel) */
                                                                                                                                                                                                                               });

                                                                                                                                                                                                                                 mv.src = GLB_URL;

                                                                                                                                                                                                                                   /* ---------- abrir / fechar ---------- */
                                                                                                                                                                                                                                     function abrir() {
                                                                                                                                                                                                                                         painel.hidden = false;
                                                                                                                                                                                                                                             botao.setAttribute("aria-expanded", "true");
                                                                                                                                                                                                                                                 tocar("Wave", 2200);
                                                                                                                                                                                                                                                     if (!chat.children.length) {
                                                                                                                                                                                                                                                           mensagem("bot", "Oi! Sou o HoloMed 💚 Pergunte algo sobre saúde que eu respondo com o conteúdo do projeto.");
                                                                                                                                                                                                                                                               }
                                                                                                                                                                                                                                                                   input.focus();
                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                       function fechar() {
                                                                                                                                                                                                                                                                           painel.hidden = true;
                                                                                                                                                                                                                                                                               botao.setAttribute("aria-expanded", "false");
                                                                                                                                                                                                                                                                                   botao.focus();
                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                       botao.addEventListener("click", function () { painel.hidden ? abrir() : fechar(); });
                                                                                                                                                                                                                                                                                         document.addEventListener("keydown", function (ev) {
                                                                                                                                                                                                                                                                                             if (ev.key === "Escape" && !painel.hidden) fechar();
                                                                                                                                                                                                                                                                                               });

                                                                                                                                                                                                                                                                                                 /* ---------- chat (busca no FAQ do dados.js) ---------- */
                                                                                                                                                                                                                                                                                                   function mensagem(quem, texto) {
                                                                                                                                                                                                                                                                                                       var div = document.createElement("div");
                                                                                                                                                                                                                                                                                                           div.className = "holomed-msg " + quem;
                                                                                                                                                                                                                                                                                                               div.textContent = texto;
                                                                                                                                                                                                                                                                                                                   chat.appendChild(div);
                                                                                                                                                                                                                                                                                                                       chat.scrollTop = chat.scrollHeight;
                                                                                                                                                                                                                                                                                                                         }

                                                                                                                                                                                                                                                                                                                           function buscarResposta(texto) {
                                                                                                                                                                                                                                                                                                                               var palavras = texto.toLowerCase().split(/[^\wà-ú]+/).filter(function (p) { return p.length > 3; });
                                                                                                                                                                                                                                                                                                                                   var melhor = null, melhorPontos = 0;
                                                                                                                                                                                                                                                                                                                                       perguntas.forEach(function (p) {
                                                                                                                                                                                                                                                                                                                                             var alvo = (p.pergunta + " " + p.resposta + " " + p.tema).toLowerCase();
                                                                                                                                                                                                                                                                                                                                                   var pontos = 0;
                                                                                                                                                                                                                                                                                                                                                         palavras.forEach(function (w) { if (alvo.indexOf(w) !== -1) pontos++; });
                                                                                                                                                                                                                                                                                                                                                               if (pontos > melhorPontos) { melhorPontos = pontos; melhor = p; }
                                                                                                                                                                                                                                                                                                                                                                   });
                                                                                                                                                                                                                                                                                                                                                                       return melhorPontos ? melhor : null;
                                                                                                                                                                                                                                                                                                                                                                         }

                                                                                                                                                                                                                                                                                                                                                                           form.addEventListener("submit", function (ev) {
                                                                                                                                                                                                                                                                                                                                                                               ev.preventDefault();
                                                                                                                                                                                                                                                                                                                                                                                   var texto = input.value.trim();
                                                                                                                                                                                                                                                                                                                                                                                       if (!texto) return;
                                                                                                                                                                                                                                                                                                                                                                                           mensagem("usuario", texto);
                                                                                                                                                                                                                                                                                                                                                                                               input.value = "";
                                                                                                                                                                                                                                                                                                                                                                                                   tocar("Thinking", 900);
                                                                                                                                                                                                                                                                                                                                                                                                       setTimeout(function () {
                                                                                                                                                                                                                                                                                                                                                                                                             var r = buscarResposta(texto);
                                                                                                                                                                                                                                                                                                                                                                                                                   if (r) {
                                                                                                                                                                                                                                                                                                                                                                                                                           mensagem("bot", r.resposta + " (Tema: " + r.tema + ")");
                                                                                                                                                                                                                                                                                                                                                                                                                                   tocar("Talk", 3500);
                                                                                                                                                                                                                                                                                                                                                                                                                                         } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                 mensagem("bot", "Não encontrei isso no conteúdo do projeto. Veja o FAQ ou procure a UBS. " +
                                                                                                                                                                                                                                                                                                                                                                                                                                                           ((textos && textos.avisoEducativo) ? textos.avisoEducativo : ""));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                   tocar("Empathy", 2600);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }, 700);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                               });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                               })();